name: Heartbeat Monitor

on:
  repository_dispatch:
    types: [heartbeat]

  schedule:
    - cron: "*/5 * * * *"

jobs:
  record-heartbeat:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'heartbeat'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update heartbeat file
        run: |
          echo "${{ github.event.client_payload.timestamp }}" > .last_heartbeat
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .last_heartbeat
          git commit -m "Update heartbeat at ${{ github.event.client_payload.timestamp }}" || echo "No changes to commit"
          git push

  check-heartbeat:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read last heartbeat
        id: read_hb
        run: |
          if [ ! -f .last_heartbeat ]; then
            echo "No heartbeat file found"
            echo "hb_time=0" >> $GITHUB_OUTPUT
          else
            hb_time=$(cat .last_heartbeat)
            echo "hb_time=$hb_time" >> $GITHUB_OUTPUT
          fi

      - name: Compare timestamps
        id: compare
        run: |
          now=$(date +%s)
          hb_time=${{ steps.read_hb.outputs.hb_time }}
          if [ "$hb_time" -eq 0 ]; then
            echo "No heartbeat ever recorded"
            echo "stale=true" >> $GITHUB_OUTPUT
          else
            diff=$((now - hb_time))
            echo "Last heartbeat was $diff seconds ago"
            if [ $diff -gt 600 ]; then
              echo "stale=true" >> $GITHUB_OUTPUT
            else
              echo "stale=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Alert failure
        if: steps.compare.outputs.stale == 'true'
        run: |
          echo "::error:: Heartbeat is stale! Last update more than 10 minutes ago."
          # place your Slack/email/Discord alert here

      - name: Restore system
        if: steps.compare.outputs.stale == 'true'
        run: |
          echo "Running restore script..."
          # put your restore logic here
